import { setNavbarItems, setActiveNavbarItemFromScroll } from './lib/navbar.js'
import { throttle } from './lib/throttle.js'
import { applyMarkdown } from './lib/markdown.js'
import { Elements } from './lib/constants.js'

void async function main() {
  await applyMarkdown()
  setNavbarItems()
  setActiveNavbarItemFromScroll()
  window.addEventListener('scroll', throttle(setActiveNavbarItemFromScroll, 100));
  setTimeout(() => Elements.Nav.classList.add('in'), 2500)

  const pp = document.querySelector('.profile-picture')
  pp.innerHTML = pp.innerHTML + /* html */`
    <div class="only-print right">
      <div>Auto generated by printing <a href="https://davidalsh.com">davidalsh.com</a></div>
      <div>Find the latest release from <a href="https://github.com/alshdavid/portfolio/releases">GitHub releases</a></div>
      <div>Check out the renderer <a href="https://github.com/alshdavid/portfolio">view source code</a></div>
    </div>
  `

  const doneEl = document.createElement('div')
  doneEl.classList.add('rendering-done-element')
  document.body.appendChild(doneEl)
}()