name: Deploy HTML

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Upload HTML to AWS
      run: |
        aws s3 rm --recursive s3://davidalsh.com
        aws s3 cp --recursive ./html s3://davidalsh.com
        aws cloudfront create-invalidation --distribution-id E1RN9EP7R6042I --paths /\*
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
